# Generated by Django 4.0.2 on 2022-02-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='Number_of_Buisness',
        ),
    ]
