# Generated by Django 4.0.2 on 2022-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Name_of_Buisness',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
