# Generated by Django 4.0.2 on 2022-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_category_name_of_buisness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Neighbourhood', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('IsOpen', models.BooleanField(default=False)),
                ('Category', models.CharField(max_length=100)),
                ('Stars', models.IntegerField(default=0, editable=False)),
                ('ReviewCount', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
