# Generated by Django 4.0.2 on 2022-02-11 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stars', models.IntegerField(default=0, editable=False)),
                ('Date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('Text', models.TextField()),
                ('Restaurant_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.restaurant')),
            ],
        ),
    ]
