# Generated by Django 4.0.2 on 2022-02-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ReviewCount',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Stars',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
