# Generated by Django 4.0.2 on 2022-02-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_alter_restaurant_reviewcount_alter_restaurant_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Restaurant_Id',
            field=models.IntegerField(),
        ),
    ]
