# Generated by Django 4.0.2 on 2022-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_alter_review_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name_of_Buisness',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ReviewCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.IntegerField(default=1),
        ),
    ]
