# Generated by Django 4.0.2 on 2022-02-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_alter_category_name_of_buisness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name_of_Buisness',
            new_name='Num_of_Buisness',
        ),
    ]
