# Generated by Django 4.0.2 on 2022-02-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_rename_name_of_buisness_category_num_of_buisness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
